version: '3.7'
services:
  front:
    build: ./front
    volumes:
      - ./front:/front
      - /front/node_modules
    ports:
      - 3000:3000
    container_name: koa_react_front
    depends_on:
      - back
  back:
    build: ./back
    volumes:
      - ./back:/back
      - /back/node_modules
    ports:
      - 8000:8000
    container_name: koa_react_back
